ARG BASE_IMAGE=quay.io/keycloak/keycloak:latest

FROM maven:3.9-eclipse-temurin-21-alpine AS otp-build

COPY keycloak-2fa-email-authenticator/ /otp-email/
RUN cd /otp-email && \
    mvn clean package

FROM $BASE_IMAGE AS target

COPY --from=otp-build /otp-email/target/keycloak-2fa-email-authenticator*.jar /opt/keycloak/providers/
RUN /opt/keycloak/bin/kc.sh build
