---
name: CI
on:
  push:
  pull_request:

jobs:
  validate:
    name: terraform lint and validate
    runs-on: ubuntu-22.04
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Validate
        run: |
          cd ecs-cluster
          terraform init -backend=false
          terraform validate

      - name: pre-commit
        uses: pre-commit/action@v3.0.0
